global:
  domain: "offli.eu"
image:
  repository: offli/dolacna-admin-api
  tag: "0.1.0-0"
  pullPolicy: IfNotPresent

# TODO do not include appsettings.{ENV} to k8s deployments - use empty appsettings and override everyting in config map. For that another env will be needed (to differ between ENV and appsettings)
aspNetCoreEnv: "Development"
issuer: "myKey"
audience: "myKey"
authenticationMode: "Enabled"
# TODO back to false
efMigrate: true