---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-admin-api
data:
  ASPNETCORE_ENVIRONMENT: "{{ .Values.aspNetCoreEnv }}"
  EF_MIGRATE: "{{ .Values.efMigrate }}"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin-api
type: Opaque
data:
  CONNECTIONSTRINGS__DOLACNACONTEXT: {{ "Server=infra-postgresql;Port=5432;Database=dolacna;User Id=test;Password=test;" | b64enc }}
