apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin-api
spec:
  selector:
    app: {{ .Release.Name }}-admin-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  