apiVersion: v2
name: majkulator
description: A platform to simplify calculations
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: postgresql
    version: 13.2.5
    repository: https://charts.bitnami.com/bitnami
